export const weatherDescKo = [
  { 201: "가벼운 비를 동반한 천둥구름", icon: "weather-lightning-rainy" },
  { 200: "비를 동반한 천둥구름", icon: "weather-lightning-rainy" },
  { 202: "폭우를 동반한 천둥구름", icon: "weather-lightning-rainy" },
  { 210: "약한 천둥구름", icon: "weather-partly-lightning" },
  { 211: "천둥구름", icon: "weather-lightning" },
  { 212: "강한 천둥구름", icon: "weather-lightning" },
  { 221: "불규칙적 천둥구름", icon: "weather-lightning" },
  { 230: "약한 연무를 동반한 천둥구름", icon: "weather-lightning" },
  { 231: "연무를 동반한 천둥구름", icon: "weather-lightning" },
  { 232: "강한 안개비를 동반한 천둥구름", icon: "weather-lightning-rainy" },
  { 300: "가벼운 안개비", icon: "weather-rainy" },
  { 301: "안개비", icon: "weather-rainy" },
  { 302: "강한 안개비", icon: "weather-rainy" },
  { 310: "가벼운 적은비", icon: "weather-rainy" },
  { 311: "적은비", icon: "weather-rainy" },
  { 312: "강한 적은비", icon: "weather-rainy" },
  { 313: "소나기와 안개비", icon: "weather-rainy" },
  { 314: "강한 소나기와 안개비", icon: "weather-rainy" },
  { 321: "소나기", icon: "weather-rainy" },
  { 500: "악한 비", icon: "weather-rainy" },
  { 501: "중간 비", icon: "weather-rainy" },
  { 502: "강한 비", icon: "weather-rainy" },
  { 503: "매우 강한 비", icon: "weather-rainy" },
  { 504: "극심한 비", icon: "weather-rainy" },
  { 511: "우박", icon: "weather-hail" },
  { 520: "약한 소나기 비", icon: "weather-rainy" },
  { 521: "소나기 비", icon: "weather-rainy" },
  { 522: "강한 소나기 비", icon: "weather-rainy" },
  { 531: "불규칙적 소나기 비", icon: "weather-rainy" },
  { 600: "가벼운 눈", icon: "weather-snowy" },
  { 601: "눈", icon: "weather-snowy" },
  { 602: "강한 눈", icon: "weather-snowy-heavy" },
  { 611: "진눈깨비", icon: "weather-snowy" },
  { 612: "소나기 진눈깨비", icon: "weather-snowy-rainy" },
  { 615: "약한 비와 눈", icon: "weather-partly-snowy-rainy" },
  { 616: "비와 눈", icon: "weather-snowy-rainy" },
  { 620: "약한 소나기 눈", icon: "weather-snowy-rainy" },
  { 621: "소나기 눈", icon: "weather-snowy-rainy" },
  { 622: "강한 소나기 눈", icon: "weather-snowy-rainy" },
  { 701: "박무", icon: "weather-fog" },
  { 711: "연기", icon: "weather-fog" },
  { 721: "연무", icon: "weather-fog" },
  { 731: "모래 먼지", icon: "weather-fog" },
  { 741: "안개", icon: "weather-fog" },
  { 751: "모래", icon: "weather-fog" },
  { 761: "먼지", icon: "weather-fog" },
  { 762: "화산재", icon: "cloudy-gusts" },
  { 771: "돌풍", icon: "weather-hurricane" },
  { 781: "토네이도", icon: "weather-hurricane" },
  { 800: "맑은 하늘", icon: "weather-sunny" },
  { 801: "약간의 구름이 낀 하늘", icon: "weather-partly-cloudy" },
  { 802: "드문드문 구름이 낀 하늘", icon: "weather-partly-cloudy" },
  { 803: "구름이 거의 없는 하늘", icon: "weather-sunny" },
  { 804: "구름으로 뒤덮인 흐린 하늘", icon: "weather-cloudy" },
  { 900: "토네이도", icon: "weather-hurricane" },
  { 901: "태풍", icon: "weather-hurricane" },
  { 902: "허리케인", icon: "weather-hurricane" },
  { 903: "한랭", icon: "weather-windy" },
  { 904: "고온", icon: "weather-sunny" },
  { 905: "바람부는", icon: "weather-windy" },
  { 906: "우박", icon: "weather-hail" },
  { 951: "바람이 거의 없는", icon: "weather-sunny" },
  { 952: "약한 바람", icon: "weather-windy" },
  { 953: "부드러운 바람", icon: "weather-windy" },
  { 954: "중간 세기 바람", icon: "weather-windy" },
  { 955: "신선한 바람", icon: "weather-windy" },
  { 956: "센 바람", icon: "weather-windy" },
  { 957: "돌풍에 가까운 센 바람", icon: "weather-windy" },
  { 958: "돌풍", icon: "weather-windy" },
  { 959: "심각한 돌풍", icon: "weather-windy" },
  { 960: "폭풍", icon: "weather-hurricane" },
  { 961: "강한 폭풍", icon: "weather-hurricane" },
  { 962: "허리케인", icon: "weather-hurricane" },
];
